version: '3'

services:
  server:
    build: .
    depends_on:
      - db
    links:
      - db
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      DB_DATABASE: ${DB_DATABASE_NAME}
    command: ["rails", "server", "-b", "0.0.0.0"]
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
